# Generated by Django 2.2.1 on 2019-06-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0002_auto_20190620_0319'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postres',
            table=None,
        ),
    ]
