# Generated by Django 2.2.1 on 2019-06-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0003_auto_20190620_0322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postres',
            table='postres',
        ),
    ]
